---
- name: Configure Docker on test-server
  hosts: test-server
  become: true
  tasks :
  - name: updating apt
    command: sudo apt-get update

  - name: Install Docker
    command: sudo apt-get install -y docker.io

  - name: Start Docker Service
    command: sudo systemctl start docker
    
  - name: To remove existing insurance-project container
    command: sudo docker rm -f my-insure 

  - name: Deploy Docker Container
    command: docker run -itd -p 8081:8081 --name my-insure sharmajagan/insurance-project:1.0
